spring:
  application:
    name: medassistant
  datasource:
    url: jdbc:postgresql://localhost:5433/medassistant
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/medassistant